version: '3.9'
services:
  db:
    image: mariadb:latest 	
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "false"
      MYSQL_DATABASE: "passbolt"
      MYSQL_USER: "passbolt"
      MYSQL_PASSWORD: "<mysqlpassword here>"
    volumes:
      - <input local path for your mysql file>:/var/lib/mysql

  passbolt:
    image: passbolt/passbolt:3.12.0-3-ce
    #Alternatively you can use rootless:
    #image: passbolt/passbolt:latest-ce-non-root
    restart: unless-stopped
    depends_on:
      - db
    environment:
      APP_FULL_BASE_URL: <enter your url here, if you are doing an ip address do that instead>
      DATASOURCES_DEFAULT_HOST: "db"
      DATASOURCES_DEFAULT_USERNAME: "passbolt"
      DATASOURCES_DEFAULT_PASSWORD: "<mysqlpassword here>"
      DATASOURCES_DEFAULT_DATABASE: "passbolt"
      EMAIL_DEFAULT_FROM_NAME: "Passbolt"
      EMAIL_DEFAULT_FROM: "your_default@emailhere.com"
      EMAIL_TRANSPORT_DEFAULT_HOST: "Yoursmtp provider"
      EMAIL_TRANSPORT_DEFAULT_PORT: "yoursmtp port"
      EMAIL_TRANSPORT_DEFAULT_USERNAME: "yoursmtpusername"
      EMAIL_TRANSPORT_DEFAULT_PASSWORD: "yoursmtppassword"
    volumes:
      - <local path for gpg key info>:/etc/passbolt/gpg
      - <local path for jwt keys>:/etc/passbolt/jwt
    command: ["/usr/bin/wait-for.sh", "-t", "0", "db:3306", "--", "/docker-entrypoint.sh"]
    ports:
      - <preferred public port>:80
      - <preferred SSL port>:443
    #Alternatively for non-root images:
    # - 80:8080
    # - 443:4433

volumes:
  database_volume:
  gpg_volume:
  jwt_volume:
